name: Coverity

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'gost-engine' || github.event_name == 'workflow_dispatch' }}
    env:
      OPENSSL_BRANCH: openssl-3.6.0
      USE_RPATH: yes
      PATCH_OPENSSL: 1
      GOST_PROVIDER_ENABLE_ONLINE_TESTS: 0

    steps:
    - uses: actions/checkout@v2
      with:
           submodules: true

    - name: Download Coverity build tool
      run: |
        wget -c -N https://scan.coverity.com/download/linux64 --post-data "token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=gost-engine" -O coverity_tool.tar.gz
        mkdir coverity_tool
        tar xzf coverity_tool.tar.gz --strip 1 -C coverity_tool
    - name: Build with Coverity build tool
      run: |
        export PATH=`pwd`/coverity_tool/bin:$PATH
        .github/before_script.sh
        cov-build --dir cov-int .github/script.sh
    - name: Submit build result to Coverity Scan
      run: |
        tar czvf cov.tar.gz cov-int
        curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} \
          --form email=chipitsine@gmail.com \
          --form file=@cov.tar.gz \
          --form version="Commit $GITHUB_SHA" \
          --form description="Build submitted via CI" \
          https://scan.coverity.com/builds?project=gost-engine